### ISSUE TITLE
Breaking 'code is law' via phoenix upgrade

### ISSUE THREAD

**Issue by hivemall** [ethereumclassic/ECIPs#377] opened 2020-09-14 07:55 UTC
see https://gist.github.com/sorpaas/72ce0618829849901e0f83bf43738ecb

Allegedly not only broke https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1088.md deployed contracts, but your idea of "code is law" is now moot.

> to change the behavior of existing contracts

broken contracts IS changed behavior, rekt & fin.

**Comment by q9f** [comment] 2020-09-14 10:52
Thanks for raising your concerns. What are you proposing? Please take the discussing to #262.

Closing as duplicate of #262 which is the discussion-to ticket for debating anything around Phoenix.

**Closed by q9f** 2020-09-14 10:52 UTC
Labels: editor: 2 duplicate
