### ISSUE TITLE
ECIP-1099 Calibrate Epoch Duration

### ISSUE THREAD

**Issue by iquidus** [ethereumclassic/ECIPs#368] opened 2020-09-10 10:24 UTC
This issue is the discussion for #367 which proposes extending epoch duration.

**Comment by q9f** [comment] 2020-09-10 11:10
Thanks for proposing this. My first thoughts:

Pro: 
* :+1: it's a good temporary 51% attack solution as it modifies ethash enough to invalidate hashrate available on nicehash et al.
* :+1: we kind of missed the activation window for ECIP-1043 DAG size limitation (epoch < 350), this is a viable solution even right now or in 2-3 months
* :+1: this will not only maintain long-term compatibility with current 4GB mining cards but also re-enable 2GB and 3GB GPU mining for a while

Con:
*  :warning: needs a hardfork
*  :warning: needs custom miner software

**Comment by q9f** [comment] 2020-09-11 18:00
moved to last call and replaces 1043. #370 #371

as per decision at call #362 (13)

**Comment by Lolliedieb** [comment] 2020-09-28 18:07
With the fork happening after 4G cards are already ruled out on epoch 383+ I wonder how remaining miners with 6G or 8G cards will react. Usually people do not choose their own butcher - I mean here in terms of the hard hit of profitability the network will take if many 4G cards (and 3G as well) will get back active. The danger is here that 8G miners vote against the consensus change and mine on a not updated node causing a chain split. 

Also I doubt that this will help much against 50% attacks, because when eth also has ruled out 4G cards likely many cards will turn of (the etc network can only be profitable for a very limited fraction of the sub 4G miners). The price determines the hashrate, not the other way around - at least as long as overall enough mining GPUs exist that could switch the network.  That said I expect only a few weeks after the action the effect of this change would be gone and the network would be attack-able as before because drawing hashrate from eth to etc would be too easy. 

I would rather push the efforts towards creating a new proof of work that is different enough from ethash.

**Comment by sjococo** [comment] 2020-09-28 18:30
I object to any changes to the dag file creation by for example as it is proposed now. In the past no change was made to let 1 GB cards mine, no change was made to let the 2 GB cards mine, no change was made to let the 3 GB cards mine. 

So now no change can be made to let the 4 GB cards mine after the DAG file size exceeds their on board memory. It is an attack to the ETC blockchain itself what grew organic and has to be maintained as it was intended.

If you want to change it, you should hard fork to a new coin and let ETC evolve and continue as it did.

**Comment by Ordfin** [comment] 2020-10-02 13:10
Weell, Just free world. In Italy you pay 0,23€/kW. This Is the Reading why I had choosen RX 470 gpus (48w/26mh) @ Wall 8 x 470 + sys l+/- 500w x 200 mh. Eth Is going pos, 4 gb cards left with ravencoins. I understand all reasons above, buy lloking @ me this would be another chance.

**Comment by navapro** [comment] 2020-10-02 14:42
> Well, Just few worlds. In Italy you pay 0,23€/kW. This Is the reasons why I had choosen RX 470 gpus (48w/26mh) @ Wall 8 x 470 + sys l+/- 500w x 200 mh. Eth Is going pos, 4 gb cards left with ravencoins. I understand all reasons above, but looking @ me this would be another chance.

Yes that is a good point, I'm a small miner with 200 GPU's most of them 4 GB I have been mining ETC for 2 years now, I know many people in similar situation, doing the DAG calibration will prevent 51% attack's at least till we switch to SHA 3, Its good for both parties that's just my opinion.

Thanks guys

**Comment by Lolliedieb** [comment] 2020-10-02 20:15
> Well, Just few worlds. In Italy you pay 0,23€/kW. This Is the reasons why I had choosen RX 470 gpus (48w/26mh) @ Wall 8 x 470 + sys l+/- 500w x 200 mh. Eth Is going pos, 4 gb cards left with ravencoins. I understand all reasons above, but looking @ me this would be another chance.

For me this is rather a reason not to do this change. I mean consider having 8G instead of 4G cards. How would you think then?
Also consider this: if ETC profitability is halving, would you still mine it in Italy? Or if only 1/4 is left would you still stay? Likely: no. But others with only 10ct or lesser (some countries have only 3ct energy cost and less) would say yes - in lack of other options they would continue, because its still profitable there while its not here.

So what is going to happen: all the 4G miners with extra low energy cost will switch from eth to etc. Since eth network is so much larger this will dump the profitability and push out all miners from countries with higher energy cost ending up in a centralization of few huge mining operations with 4G farms in cheap power countries left. That might be happy - but loosing mining community of potential 8G miners everywhere else is worth it? I do not think so.

**Comment by sjococo** [comment] 2020-10-02 21:00
> So what is going to happen: all the 4G miners with extra low energy 
> cost will switch from eth to etc. Since eth network is so much larger 
> this will dump the profitability and push out all miners from 
> countries with higher energy cost ending up in a centralization of 
> few huge mining operations with 4G farms in cheap power countries 
> left. That might be happy - but loosing mining community of 
> potential 8G miners everywhere else is worth it? I do not think so.

Yup, and there is your more likely 51% attack by a few large miners after ETH reaches 4 GB DAG file throwing all their hashpower at ETC.

Looked at the site of HiveOS for statistics https://hiveos.farm/statistics and saw there are 50% 8GB AMD cards. Only 6% of the total hashrate of AMD was rented to Nicehash. 76% was on ETH and 2% at ETC. Everybody understands what happens when 4 GB cards cannot mine ETH anymore, but can mine ETC...

**Comment by navapro** [comment] 2020-10-02 21:32
> > Well, Just few worlds. In Italy you pay 0,23€/kW. This Is the reasons why I had choosen RX 470 gpus (48w/26mh) @ Wall 8 x 470 + sys l+/- 500w x 200 mh. Eth Is going pos, 4 gb cards left with ravencoins. I understand all reasons above, but looking @ me this would be another chance.
> 
> For me this is rather a reason not to do this change. I mean consider having 8G instead of 4G cards. How would you think then?
> Also consider this: if ETC profitability is halving, would you still mine it in Italy? Or if only 1/4 is left would you still stay? Likely: no. But others with only 10ct or lesser (some countries have only 3ct energy cost and less) would say yes - in lack of other options they would continue, because its still profitable there while its not here.
> 
> So what is going to happen: all the 4G miners with extra low energy cost will switch from eth to etc. Since eth network is so much larger this will dump the profitability and push out all miners from countries with higher energy cost ending up in a centralization of few huge mining operations with 4G farms in cheap power countries left. That might be happy - but loosing mining community of potential 8G miners everywhere else is worth it? I do not think so.

Well you may be correct but imagine what will happen when all that 4G cards mine ravencoin or beam or something else its going to be even lower profitability. I'm in Canada I have 8 cents/kwh. Even if the 4G cards can mine the 8G cards will be faster and more efficient so even If you have 8G card you will be profitable, ravencoin is already 1/2 the profitability of ETC so I will keep mining.

The same issue with low electric cost is an issue even with 8G cards too.

**Comment by wpwrak** [comment] 2020-10-02 21:36
Once ECIP-1049 activates, ETC will be the most profitable coin for 3 GB hardware. Once ETH's DAG goes over 4 GB (i.e., in December), ETC will be the most profitable coin for 4 GB hardware, too. If ETC is the most profitable coin for them, this is a strong incentive for miners to be loyal.

Also, you don't need to be a majority chain to be safe from 51% attacks - it's sufficient to have enough honest hash rate to match the hash rate the attacker controls plus any vacant hash rate they can pick up. Thus, even the relatively small changes we can expect ECIP-1049 to produce will greatly raise the barrier for attackers.

Furthermore, while the software change is small, it is significant enough to prevent current hash rate rentals from being able to redirect "generic" Ethash rate across coins. Even if they were to implement a way to propagate this parameter to their miners (which would involve changing the mining software and also their pool protocol - a departure from the current low barrier of access), the difference would still be visible to them, so they could easily implement checks on their end. We already have practical evidence that hash rate brokers are interested in proactively preventing their services from being be abused, so we'll all be working towards the same goal here.

**Comment by navapro** [comment] 2020-10-02 21:36
> > So what is going to happen: all the 4G miners with extra low energy
> > cost will switch from eth to etc. Since eth network is so much larger
> > this will dump the profitability and push out all miners from
> > countries with higher energy cost ending up in a centralization of
> > few huge mining operations with 4G farms in cheap power countries
> > left. That might be happy - but loosing mining community of
> > potential 8G miners everywhere else is worth it? I do not think so.
> 
> Yup, and there is your more likely 51% attack by a few large miners after ETH reaches 4 GB DAG file throwing all their hashpower at ETC.
> 
> Looked at the site of HiveOS for statistics https://hiveos.farm/statistics and saw there are 50% 8GB AMD cards. Only 6% of the total hashrate was rented to Nicehash. 76% was on ETH and 2% at ETC. Everybody understands what happens when 4 GB cards cannot mine ETH anymore, but can mine ETC...

But acording to hive os a good 40% of all cards are 4GB, that means they will come to ETC, which is good because that will make the network more secure and also build a larger community around ETC.

**Comment by sjococo** [comment] 2020-10-02 21:43
> 
> 
> > > So what is going to happen: all the 4G miners with extra low energy
> > > cost will switch from eth to etc. Since eth network is so much larger
> > > this will dump the profitability and push out all miners from
> > > countries with higher energy cost ending up in a centralization of
> > > few huge mining operations with 4G farms in cheap power countries
> > > left. That might be happy - but loosing mining community of
> > > potential 8G miners everywhere else is worth it? I do not think so.
> > 
> > 
> > Yup, and there is your more likely 51% attack by a few large miners after ETH reaches 4 GB DAG file throwing all their hashpower at ETC.
> > Looked at the site of HiveOS for statistics https://hiveos.farm/statistics and saw there are 50% 8GB AMD cards. Only 6% of the total hashrate was rented to Nicehash. 76% was on ETH and 2% at ETC. Everybody understands what happens when 4 GB cards cannot mine ETH anymore, but can mine ETC...
> 
> But acording to hive os a good 40% of all cards are 4GB, that means they will come to ETC, which is good because that will make the network more secure and also build a larger community around ETC.

ETC getting 20 times or more hashpower from a few large mining farms that can compete with their low electricity cost is a higher chance of a 51% attack. Small miners in Europe and USA cannot compete with the tanked profitability of ETC.

**Comment by Ordfin** [comment] 2020-10-02 21:47
I see your points, but then, left aside my particular high-costs energy position, I think there is much more to say, starting from MESS and ending with keccak256: one can't talk against DAG size reduction without adding the two above as a whole, and this is why ECIPs 1099 and 1100 are there together.

ETC needs a boost, but it's not just a security matter: it's an empaty matter, like said.

Let's say ETC rejects DAG reduction: so, ETC will be left with MESS and keccak256 to solve the 51% attacks issue for at least 2 years. Meanwhile, I'd like to know from where a significant hashing power boost is supposed to come from to ETC, given that to see the 1st keccak ASICS we'll have to wait a bit and that, being ETH POW still there, people will wait before switching.

There are 20 Ths waiting a TRUE target to mine (alternatives are not qualified), but they won't wait long: people have started already trying to switch to 6-8 gb cards,  (hardware prices show it clearly), and actually I can't see valid reasons why the same percentages showed by HiveOs won't be valid for the short-mid term to those "switchers". This is an empaty matter.

MESS and Kecaak256 are the answer to the 51% issue. This is a security matter.

All trading platforms, as we all know, have already applied large delays to ETC, and this goes to security.

Now it's time to empaty.

**Comment by wpwrak** [comment] 2020-10-03 02:50
Edit: I wrote "once ECIP-1049 activates, [...] 3 GB [...]". That should of course have been "ECIP-1099". I edited it, but the mails that get sent out don't include later changes. Sorry for the confusion.

**Comment by TheEnthusiasticAs** [comment] 2020-10-03 09:41
This ECIP can be moved to "accepted" as the review date ended on 10-02 according to https://ecips.ethereumclassic.org/ECIPs/ecip-1099

**Comment by iquidus** [comment] 2020-10-03 10:05
This discussion is in regards to 1099, only. 1049 and 1100, have their own discussion threads. 1099 is not trying to address the attacks (nor is 1049 for that mater), as outlined in the proposal, it's intent is to reduce the DAG size and future growth to better support GPUs in use by existing miners today.

In regards to ETH miners attacking ETC once (read if) ETH2 finally launches, this makes little sense, it would be one of the more profitable chains to mine with GPUs, attacking would be akin to shooting oneself in the foot. Attacks have been coming from rentals, they have not been coming from miners that have invested long term in their own hardware. Even if this is a concern, the only mitigation would be to dilute the attackers hashrate, with more hash, from more GPUs..

**Comment by Lolliedieb** [comment] 2020-10-04 16:59
Dropping here my last thoughts about this - and will shut up after ;) Had it posted originally in discord group, but want to have it documented here as well:

I believe in the end ECIP 1099 will not resolve the "attack-able" over Nicehash issue. For the following reason:
Back in summer 2018 we had the same issues (a bigger network with same PoW, Nicehash and 51% attacks on the smaller caps) on many Equihash coins (BTG, ZEL and so on, just to name a few) that had same pow as ZCash.
They kind of all decided to move to an other Equihash variant (144/5) and all use a different personalization string that makes to pow individual for each coin.

But: after a while Nicehash introduced this string as additional stratum parameter. So mining software understanding it were able to switch between the coins even without reconnecting. And to be serious: there is so much hr going over Nicehash that neither pools nor miner devs can allow themselves really  to ignore their proposed changes.

So history might repeat here: the moment they decide to send out that one bit info - to use eth or etc ecip 1099 seeding scheme - miner softwares will be able to switch again just while running. And every 8G card that then can mine eth can also do etc. So from that moment on the protection will be same as now without the ECIP.

So well ... not actually a concern about the ECIP - but rather rebutting the argument why this change might help at all.

**Comment by navapro** [comment] 2020-10-04 17:28
Hi sorry guys. Can someone tell me what decision was made about this on the meeting.
Thanks

**Comment by TheEnthusiasticAs** [comment] 2020-10-04 18:00
> Hi sorry guys. Can someone tell me what decision was made about this on the meeting.
> Thanks

Hi @navapro. From the ETC Core Devs Call 14 on 25th of September:
- ECIP 1099 remains in "last call" but new block numbers (pushed back to allow besu to implement it), this will move to "accepted" next friday (2nd of October) unless you raise your concerns, core developers start working on implementations and preparing releases, see also the #376. The activation is on the block height 11_700_000.

Since today this proposal should be moved to "accepted" state. Awaiting for ECIP-Editors :-)

**Comment by GrshkvMkhl** [comment] 2020-10-04 18:39
> > Hi sorry guys. Can someone tell me what decision was made about this on the meeting.
> > Thanks
> 
> Hi @navapro. From the ETC Core Devs Call 14 on 25th of September:
> 
> * ECIP 1099 remains in "last call" but new block numbers (pushed back to allow besu to implement it), this will move to "accepted" next friday (2nd of October) unless you raise your concerns, core developers start working on implementations and preparing releases, see also the #376. The activation is on the block height 11_700_000.
> 
> Since today this proposal should be moved to "accepted" state. Awaiting for ECIP-Editors :-)

So DAG should decrease in about 58 days?

**Comment by navapro** [comment] 2020-10-04 18:41
> > Hi sorry guys. Can someone tell me what decision was made about this on the meeting.
> > Thanks
> 
> Hi @navapro. From the ETC Core Devs Call 14 on 25th of September:
> 
> * ECIP 1099 remains in "last call" but new block numbers (pushed back to allow besu to implement it), this will move to "accepted" next friday (2nd of October) unless you raise your concerns, core developers start working on implementations and preparing releases, see also the #376. The activation is on the block height 11_700_000.
> 
> Since today this proposal should be moved to "accepted" state. Awaiting for ECIP-Editors :-)

Thanks guys I'm exited to see this !

**Comment by zmitton** [comment] 2020-10-13 12:04
Although almost ever comment seems to be in opposition to this ECIP, I'll add my own reasons to the discussion.
 - This is obviously contentious. And it is a hard fork. That makes it the most dangerous type of change.
 - It does not solve the 51% attack problem in any viable way. The only argument I given for this was "modifies ethash enough to invalidate hashrate available on nicehash". This argument involves a specific company (who by the way could easily add the  feature) A cryptocurrency's security cannot rely on what a single company's feature set may of may not currently be.

**Comment by NickNick-tech** [comment] 2020-10-14 13:25
If ECIP 1099 did not have much support it would not currently be in accepted status.
- This is a very simple change that is easy to implement and that does not introduce anything new compared to what currently exists. The goal is to keep the existing 4 GB hardware and to attract new ones that soon will not be able to mine ETH. The right place to discuss contentious hard fork is ECIP 1049 which is 1000 times more expensive and harder to implement safely and FAIRLY. Don't be hypocritical here.
- It solves the 51% attack problem as follows. 4 GB cards are currently represented by 48% of all cards (source: https://hiveos.farm/statistics/). Due to the dag size increase ETH will soon be left without 120 Th/s. If, for example, only 30 Th/s pass on the ETC it will make it much more resistant to 51% attack. Especially considering that an attacker, due to MESS, will need 31 times more hashrate than before to carry out a 51% attack. It is logical to expect that these 30 Th/s will directly mine ETC, without Nicehash, as they are currently directly mining ETH. Taking this fact into account and the fact that MESS has been implemented, this greatly reduces the danger of Nicehash and thus the worry of whether Nicehash will have an etchash button. An increase in the hashrate will affect the price increase because then investors and miners will buy the ETC instead of mining it 10-15 times longer then now due to the increased hashrate.

**Comment by NickNick-tech** [comment] 2020-10-14 13:29
If there are no technical limitations, which I do not see, I think it is better that the dag epoch instead of lasting twice as long (x2) lasts x3 or x4 (as much as possible). I don't see any technical obstacles to the epoch lasting instead of the planned 8, say 16 days. The correction is trivial - put x4 in the code instead of x2. The reason I suggest this is that it’s not nice, nor professionally good for business and customer engagement, to artificially deny someone with weaker hardware to mine if they want to. It is much more natural and normal for people to stop mining on their own when it is no longer profitable for them, and that does not necessarily mean that it will be in 3 years. As we can see from the empirical evidence that the hardware from 3 years ago is still profitable.

**Comment by NickNick-tech** [comment] 2020-10-14 19:50
Anyone who has previously purchased 8 GB cards, counting on elimination of 4 GB cards, will be able to make the planned higher earnings by mining ETH when its dag size exceeds 4 GB (December 20). In addition, 4 GB cards will not be able to mine ETC from approximately October 20 to November 26. This is also an opportunity for 8 GB cards.

**Comment by zmitton** [comment] 2020-10-17 15:38
There is a huge group of silent participants that disagree with this hard fork. 1099 is particularly bad because it won't fix the problems it purports to, which will lead to more contentious hard forks in the future (again to be made while ignoring politically inactive users).

**Comment by erdnapa** [comment] 2020-10-17 16:21
Those 'silent participants' should make their voice heard then. Just claiming they exist isn't enough.
Did you read ECIP-1099? https://ecips.ethereumclassic.org/ECIPs/ecip-1099
It's goal is keeping 4GB GPUs on the network, and that is exactly what it achieves. 
No mention of other problems.

**Comment by iquidus** [comment] 2020-10-17 17:23
As stated in the ecip, the motivation/rationale behind this proposal is the following (in its entirety)

```
The original intent of the DAG was to provide ASIC resistance to the mining protocol in order to prevent centralization of mining distributions and thereby provide for an objectively fair distribution of tokens. As evident by ASICs being developed that are capable of matching current GPU miners while being more energy efficient, the DAG has succeeded in leveling the playing field between GPU incumbents and ASIC challengers, avoiding ASIC takeover and domination, and leading to a competitive and large mining ecosystem. However the original parameters are proving too aggressive, resulting in obsoleting support for GPUs still in wide use today by miners.

Calibrating these parameters to better reflect todays hardware markets and mining ecosystem will bring the DAG growth back in sync with commonly used GPUs. Allowing the DAG system to continue to serve it's purpose far into the future.
```

```
At current epoch (372) the DAG size is 3.91 GB. 4GB GPUs are getting obsoleted while they still make up a significant amount of ethash hashrate. Activating this change at epoch 376 (for example), would reduce the DAG size from 3.94GB to 2.47GB. With the reduced growth rate, 4GB GPUs will remain supported for an additional 3+ years.
```

The only problem this ecip is solving is aggressive DAG growth, by a) reseting the DAG to half its current size, and b) halving the growth rate moving forward. It is not attempting to solve anything else.

**Comment by q9f** [comment] 2020-10-20 12:14
collecting resources for etchash in https://github.com/eth-classic/etchash

**Comment by gitr0n1n** [comment] 2020-10-25 07:03
Very excited for this proposal to go live! So many positives for the network.

+ 3GB care moving to ETC in November
+ 4GB card moving to ETC in December
= increase in lower bound hash rate.

ETC APEX chain for these lower capacity cards = Big network security appreciation.

Likely a positive for price appreciation as well with long term miner capture. Great proposal @iquidus !

**Comment by stevanlohja** [comment] 2020-10-26 18:45
> As stated in the ecip, the motivation/rationale behind this proposal is the following (in its entirety)
> 
> ```
> The original intent of the DAG was to provide ASIC resistance to the mining protocol in order to prevent centralization of mining distributions and thereby provide for an objectively fair distribution of tokens. As evident by ASICs being developed that are capable of matching current GPU miners while being more energy efficient, the DAG has succeeded in leveling the playing field between GPU incumbents and ASIC challengers, avoiding ASIC takeover and domination, and leading to a competitive and large mining ecosystem. However the original parameters are proving too aggressive, resulting in obsoleting support for GPUs still in wide use today by miners.
> 
> Calibrating these parameters to better reflect todays hardware markets and mining ecosystem will bring the DAG growth back in sync with commonly used GPUs. Allowing the DAG system to continue to serve it's purpose far into the future.
> ```
> 
> ```
> At current epoch (372) the DAG size is 3.91 GB. 4GB GPUs are getting obsoleted while they still make up a significant amount of ethash hashrate. Activating this change at epoch 376 (for example), would reduce the DAG size from 3.94GB to 2.47GB. With the reduced growth rate, 4GB GPUs will remain supported for an additional 3+ years.
> ```
> 
> The only problem this ecip is solving is aggressive DAG growth, by a) reseting the DAG to half its current size, and b) halving the growth rate moving forward. It is not attempting to solve anything else.

What's the plan when the Dag returns to today's current level?

**Comment by bobsummerwill** [comment] 2020-10-26 20:00
>> What's the plan when the Dag returns back to where we are today?

Well, my personal hope would be that 1049 is implemented before that happens, so the DAG is no longer a concern.

If that does not happen, and we remain in "ASIC resistant land" then this constant will end up being much like the difficulty bomb in ETH.  Sometime to be considered every few years and either left as-is or reduced again.   There is no permanence here, that is for sure.   We are choosing to intervene.

**Comment by gitr0n1n** [comment] 2020-10-27 10:41
> Well, my personal hope would be that 1049 is implemented before that happens, so the DAG is no longer a concern.

This 1049 proposal is dead on arrival. No matter how hard you try to shill it @bobsummerwill Please go work on a new coin for that. You've tried to push it through and its not gaining traction. Put ETC Coop resources to something productive please. Your org is flooding every outlet with this spam.

**Comment by q9f** [comment] 2020-10-27 12:54
I think everyone is entitled to have an opinion here and Bob introduced his statement with the modifier "personal." So there is no need to be bashing either Bob or the ETC Coop.

**Comment by LuKePicci** [comment] 2020-11-07 13:02
Let me point out that the DAG size reduction will also restore original hashrate performance of some 8GB nVidia Pascal GPUs affected by insufficient TLB design. This consists in up to a 27% hr boost for them.

I don't know how many of the active 8GB miners are currently running on those GPUs, but I'd like to make some considerations about them:
- the DAG size reduction would protect their planned investments
- the hashpower they're currently providing to Ethash pools depends on the coin they mine, this means the above mentioned hr boost will affect both their current ETC hashpower and any they would move to ETC from ETH

**Comment by slavserver** [comment] 2020-11-18 12:13
> > Ну, всего несколько миров. В Италии вы платите 0,23€ / кВт. Вот почему я выбрал графические процессоры RX 470 (48w / 26mh) @ Wall 8 x 470 + sys l+/- 500w x 200 mh. Eth собирается pos, 4 ГБ карт осталось с ravencoins. Я понимаю все вышеперечисленные причины, но, глядя на меня, это был бы еще один шанс.
> 
> Да, это хороший момент, я маленький майнер с 200 графическими процессорами, большинство из которых 4 ГБ, я занимаюсь майнингом и т. д. Уже 2 года, я знаю многих людей в подобной ситуации, выполнение калибровки DAG предотвратит 51% атак, по крайней мере, пока мы не перейдем на SHA 3, это хорошо для обеих сторон, это просто мое мнение.
> 
> Спасибо ребята

hello ... remember ubiqhash and how it fell in price ... you would like only video cards to be mining ... and what, your coin went to the bottom ...
Now imagine, you are doing etchash, you are planning to attract 3 gigabytes, 4 gigabytes of video cards to mining .... and what's the point? these video cards, compared to modern ones, consume more electricity ... a modern 8 gigabyte card consumes 70 watts .... while older cards consume 150-180 watts of energy ..., you absolutely stupid ???? you as ubiqhash destroy the coin .... you were asked - pirlguard

привет... вспомните ubiqhash икак он упал в цене..... вы, хотели, что бы майнингом занимались только видеокарты..... и что, ваша монета ушла на дно....
а теперь представьтье, вы делаете etchash , вы планируте привлечь к майнингу видеокарты 3 гигабата, 4 гигабайта.... а в чем смысл? эти видео карты, по сравнению с современныменными, потребляют больше электричичесва..... современная карта на 8 гигабайт, потребляет 70 ватт.... в то время как более древние карты потребляют 150- 180 ватт энергиии...., вы совсем тупые???? вы, как ubiqhash уничтожите монету.... вам было предложено - pirlguard

**Comment by slavserver** [comment] 2020-11-18 12:17
> > Ну, всего несколько миров. В Италии вы платите 0,23€ / кВт. Вот почему я выбрал графические процессоры RX 470 (48w / 26mh) @ Wall 8 x 470 + sys l+/- 500w x 200 mh. Eth собирается pos, 4 ГБ карт осталось с ravencoins. Я понимаю все вышеперечисленные причины, но, глядя на меня, это был бы еще один шанс.
> 
> Да, это хороший момент, я маленький майнер с 200 графическими процессорами, большинство из которых 4 ГБ, я занимаюсь майнингом и т. д. Уже 2 года, я знаю многих людей в подобной ситуации, выполнение калибровки DAG предотвратит 51% атак, по крайней мере, пока мы не перейдем на SHA 3, это хорошо для обеих сторон, это просто мое мнение.
> 
> Спасибо ребята

**Comment by recurvolution** [comment] 2020-11-18 15:55
At least for Nvidia cards I see that total wattage per hash is not that different.  My gtx 1050 ti cards with 4gb of ram max out at 75 watts a piece typically stable in the 60 watt range.  My newer 2070 supers with 8 gb are drawing 215 watts.  Cost of operation for equivalent hash rate is almost the same.
The biggest thing that prevents me from mining ETC even with my 8gb cards is that I cannot find an exchange that will accept deposits at the moment due to the August 51% attacks.  Which means from an earning perspective ETC has no liquid value for miners.  You can buy and trade ETC within the exchange you just cannot deposit your mining income.
Hard to attract miners when the earnings are inaccessible.

**Comment by recurvolution** [comment] 2020-11-18 16:14
@iquidus I see you list ethminer on the https://ecips.ethereumclassic.org/ECIPs/ecip-1099 page and a link to https://github.com/iquidus/ethminer/ on the https://github.com/eth-classic/etchash page as being updated for the Thanos upgrade.  Is this actively being updated?  The iquidus/ethminer project is a relatively old fork of ethereum-mining/ethminer and over at ethereum-mining/ethminer it was stated that they are not actively updating the code in the issues, https://github.com/ethereum-mining/ethminer/issues/2080.

**Comment by Ordfin** [comment] 2020-11-18 22:19
Just my 2 cents.

**@recurvolution**: About the liquid value, there are many changes going on in these days. I know mining sites which restored etc autoexchange to btc, so you can mine ETC today being paid in btc or deciding to keep mined ETCs to change them later for better value. I think that exchanges won't take long to come back to normal aswsell.

**@slavserver**: actually, talking about GPUs, the best ROIs belong to Radeon R9 FURY 4gb and RX470 4gb cards. A modern 6/8gb card consumes less power but its own ROI, even with higher hashrates, is at least 15-20x times more. Sure, one can take into consideration the reselling value of the newer hardware but to do what? To buy newer gpus @ higher prices with same (or worst) ROI? Radeon VII teached many, and I was one of those.  Perhaps one at that point could buy one or more ASICs, but then, with reduced DAG, some "old fashioned" fellows such as  E3s will come back into play with awesome ROI. Another one:  ASICs for a low-rate increasing DAG size coin will be more appealing for both developers and miners. I really don't get your points. Sorry.

**Closed** 2021-02-01 12:41 UTC
Labels: status:3 accepted, type: std-core
